### ISSUE TITLE
downloader.c compile error

### ISSUE THREAD

**Issue by kliffgomel** [gpac/gpac#1212]
Compile with mingw32 gcc 8.3.0 rev 1
[ab-suite.make.log](https://github.com/gpac/gpac/files/2929885/ab-suite.make.log)
[config.log](https://github.com/gpac/gpac/files/2929887/config.log)

D:/ffmpeg-autobuild/build/gpac-git/src/utils/downloader.c: In function 'gf_dm_sess_setup_from_url':
D:/ffmpeg-autobuild/build/gpac-git/src/utils/downloader.c:1151:11: error: 'GF_DownloadSession' {aka 'struct __gf_download_session'} has no member named 'ssl'
   if (sess->ssl) {
           ^~
D:/ffmpeg-autobuild/build/gpac-git/src/utils/downloader.c:1152:4: warning: implicit declaration of function 'SSL_shutdown' [-Wimplicit-function-declaration]
    SSL_shutdown(sess->ssl);
    ^~~~~~~~~~~~
D:/ffmpeg-autobuild/build/gpac-git/src/utils/downloader.c:1152:21: error: 'GF_DownloadSession' {aka 'struct __gf_download_session'} has no member named 'ssl'
    SSL_shutdown(sess->ssl);
                     ^~
D:/ffmpeg-autobuild/build/gpac-git/src/utils/downloader.c:1153:4: warning: implicit declaration of function 'SSL_free'; did you mean 'gf_free'? [-Wimplicit-function-declaration]
    SSL_free(sess->ssl);
    ^~~~~~~~
    gf_free
D:/ffmpeg-autobuild/build/gpac-git/src/utils/downloader.c:1153:17: error: 'GF_DownloadSession' {aka 'struct __gf_download_session'} has no member named 'ssl'
    SSL_free(sess->ssl);
                 ^~
D:/ffmpeg-autobuild/build/gpac-git/src/utils/downloader.c:1154:8: error: 'GF_DownloadSession' {aka 'struct __gf_download_session'} has no member named 'ssl'
    sess->ssl = NULL;
        ^~

**Comment by jeanlf** [comment]
should now be fixed, thanks for the report
