### ISSUE TITLE
Compilation failed with Clang11 on OSX

### ISSUE THREAD

**Issue by zhoub** [gpac/gpac#1534]
Hi

Tried to use GPAC  on OSX 10.15.4 in C++11 program. Using latest commit `e4dc0015293571aeef81817b486d16ff5673db8f` of master branch.

Using the following compiler toolchain
```bash
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Once wrote `#include <gpac/avparse.h>` in source file, the compiler reported error as this
```bash
In file included from /Users/user/Document/gpac-build/dist-master/include/gpac/avparse.h:56:
In file included from /Users/user/Document/gpac-build/dist-master/include/gpac/bitstream.h:48:
In file included from /Users/user/Document/gpac-build/dist-master/include/gpac/tools.h:33:
/Users/user/Document/gpac-build/dist-master/include/gpac/setup.h:512:16: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define LLD "%"LLD_SUF
               ^
                
/Users/user/Document/gpac-build/dist-master/include/gpac/setup.h:514:16: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define LLU "%"LLU_SUF
               ^
                
/Users/user/Document/gpac-build/dist-master/include/gpac/setup.h:516:16: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define LLX "%"LLX_SUF
```

On Ubuntu 16 with GCC540, here is just warning not error. I think it's best to have a proper support for C++1x.

Thanks a lot !

**Comment by jeanlf** [comment]
added space, can you check if that now compiles ?

**Comment by aureliendavid** [comment]
If you're using the headers from a c++ program you should include them in a `extern "C" { .. }` block

**Comment by zhoub** [comment]
> added space, can you check if that now compiles ?

Oh yes, it works, thanks !

**Comment by zhoub** [comment]
> If you're using the headers from a c++ program you should include them in a `extern "C" { .. }` block

It works on my Ubuntu 18 with GCC 5.4.0 .
