### ISSUE TITLE
Error while building Gpac for Android: Unknown or unsupported ARM architecture

### ISSUE THREAD

**Issue by SrujithPoondla** [gpac/gpac#677]
```
/home/xyz/gpac_extra_libs/build/android/jni/../../../libjpg/jerror.c:78:3: note: 
      include the header <stdlib.h> or explicitly provide a declaration for
      'exit'
1 warning generated.
[armeabi] Compile arm    : jpegdroid <= jfdctflt.c
[armeabi] Compile arm    : jpegdroid <= jfdctint.c
[armeabi] Compile arm    : jpegdroid <= jidctflt.c
[armeabi] Compile arm    : jpegdroid <= jidctred.c
[armeabi] Compile arm    : jpegdroid <= jquant1.c
[armeabi] Compile arm    : jpegdroid <= jquant2.c
[armeabi] Compile arm    : jpegdroid <= jutils.c
[armeabi] Compile arm    : jpegdroid <= jmemmgr.c
[armeabi] Compile arm    : jpegdroid <= jmem-android.c
/home/xyz/gpac_extra_libs/build/android/jni/jpegdroid/jmem-android.c:135:5: warning: 
      implicit declaration of function 'unlink' is invalid in C99
      [-Wimplicit-function-declaration]
    unlink(path);
    ^
/home/xyz/gpac_extra_libs/build/android/jni/jpegdroid/jmem-android.c:141:45: warning: 
      implicit declaration of function 'getpid' is invalid in C99
      [-Wimplicit-function-declaration]
    snprintf(path, 1023, "/sdcard/.%d.tmp", getpid());
                                            ^
2 warnings generated.
[armeabi] Compile arm    : jpegdroid <= jfdctfst.c
[armeabi] Compile arm    : jpegdroid <= jidctint.c
[armeabi] Compile arm    : jpegdroid <= jidctfst.S
In file included from /home/xyz/gpac_extra_libs/build/android/jni/jpegdroid/jidctfst.S:17:
/home/xyzAndroid/Sdk/ndk-bundle/platforms/android-24/arch-arm/usr/include/machine/cpu-features.h:52:6: error: 
      Unknown or unsupported ARM architecture
#    error Unknown or unsupported ARM architecture
     ^
1 error generated.
make: *** [/home/xyz/gpac_extra_libs/build/android/obj/local/armeabi/objs/jpegdroid/jpegdroid/jidctfst.o] Error 1

```

**Comment by SrujithPoondla** [comment]
@jeanlf could you help me in solving this issue

**Comment by jeanlf** [comment]
this seems to be a regression due to latests NDKs. For now you need to make sure you have the line:
`ANDROID_JPEG_NO_ASSEMBLER := true`
uncommented in file build/android/jni/lib_jpegdroid.mk

jean

**Comment by SrujithPoondla** [comment]
i am getting this error while following this (https://github.com/gpac/gpac/blob/master/applications/osmo4_android_studio/app/src/main/jni/README.txt)

```

4 warnings generated.
[armeabi] SharedLibrary  : libgm_droid_cam.so
[armeabi] Install        : libgm_droid_cam.so => libs/armeabi/libgm_droid_cam.so
[armeabi] Compile thumb  : gm_droid_mpegv <= droid_mpegv.c
/home/xyz/gpac/build/android/jni/modules/../../../../modules/droid_mpegv/droid_mpegv.c:180:12: warning: 
      using the result of an assignment as a condition without parentheses
      [-Wparentheses]
  ...if ( res = (*GetJavaVM())->AttachCurrentThread(GetJavaVM(), &env, NULL) )
          ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xyz/gpac/build/android/jni/modules/../../../../modules/droid_mpegv/droid_mpegv.c:180:12: note: 
      place parentheses around the assignment to silence this warning
  ...( res = (*GetJavaVM())->AttachCurrentThread(GetJavaVM(), &env, NULL) )
           ^
       (                                                                 )
/home/xyz/gpac/build/android/jni/modules/../../../../modules/droid_mpegv/droid_mpegv.c:180:12: note: 
      use '==' to turn this assignment into an equality comparison
                if ( res = (*GetJavaVM())->AttachCurrentThread(GetJavaVM...
                         ^
                         ==
/home/xyz/gpac/build/android/jni/modules/../../../../modules/droid_mpegv/droid_mpegv.c:389:3: error: 
      non-void function 'ThreadRun' should return a value [-Wreturn-type]
                return;
                ^
/home/xyz/gpac/build/android/jni/modules/../../../../modules/droid_mpegv/droid_mpegv.c:399:3: error: 
      non-void function 'ThreadRun' should return a value [-Wreturn-type]
                return;
                ^
1 warning and 2 errors generated.
make: *** [/home/xyz/gpac/build/android/obj/local/armeabi/objs/gm_droid_mpegv/__/__/__/__/modules/droid_mpegv/droid_mpegv.o] Error 1

```

Is this also because of NDK ? Do i have to modify anything?

**Comment by jeljeli** [comment]
In android-ndk-rxx/build/core/init.mk change the line 639 
from `NDK_TOOLCHAIN_VERSION := clang`
to `NDK_TOOLCHAIN_VERSION := 4.9`
to build with gcc4.9 instead of clang

**Comment by SrujithPoondla** [comment]
Thanks @jeljeli
