### ISSUE TITLE
gpac-2.2.0 fails to compile with ffmpeg-6.0 release.

### ISSUE THREAD

**Issue by leigh123linux** [gpac/gpac#2406]
Link to build logs.

https://koji.rpmfusion.org/koji/taskinfo?taskID=585584

```
gcc -I"/builddir/build/BUILD/gpac-2.2.0/include"  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_LARGEFILE_SOURCE=1 -D_GNU_SOURCE=1 -I/usr/include/ffmpeg -Wall -fno-strict-aliasing -Wno-pointer-sign -fPIC -DPIC -msse2 -DNDEBUG -std=gnu99 -Wno-deprecated -Wno-deprecated-declarations -Wno-int-in-bool-context -DGPAC_HAVE_CONFIG_H -I"/builddir/build/BUILD/gpac-2.2.0" -fvisibility="hidden"    -I/usr/include/ffmpeg -c -o filters/ff_mx.o filters/ff_mx.c
filters/ff_mx.c: In function 'ffmx_close_seg':
filters/ff_mx.c:506:72: error: 'AVIOContext' has no member named 'written'
  506 |         evt.seg_size.media_range_end = ctx->muxer->pb ? (ctx->muxer->pb->written-1) : 0;
      |                                                                        ^~
filters/ff_mx.c: In function 'ffmx_configure_pid':
filters/ff_mx.c:1016:55: error: 'const struct AVOutputFormat' has no member named 'query_codec'
 1016 |         if (ctx->muxer->oformat && ctx->muxer->oformat->query_codec) {
      |                                                       ^~
filters/ff_mx.c:1017:42: error: 'const struct AVOutputFormat' has no member named 'query_codec'
 1017 |                 res = ctx->muxer->oformat->query_codec(ff_codec_id, 1);
      |                                          ^~
make[1]: *** [../config.mak:183: filters/ff_mx.o] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/gpac-2.2.0/src'
make[1]: *** Waiting for unfinished jobs....
```

See.

https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/9b8a398930df6606f6314b07c66605f44a8cb0eb

**Comment by marillat** [comment]
One issue has been fixed in commit a75cd2866a490abc5df1fc5da102785303407115 but reverted in commit 70bc8f6877a9651a0fc4c1b14e8cd2bf2f07a068

But there is a second issue with ffmpeg 6 related to changes in  AVOutputFormat https://github.com/FFmpeg/FFmpeg/commit/59c9dc82f450638a3068deeb1db5c56f6d155752

**Comment by jeanlf** [comment]
now fixed on master, thanks for the report

**Comment by marillat** [comment]
Thanks for the fix.

**Comment by leigh123linux** [comment]
Thanks for fixing the issue.

**Comment by jeanlf** [comment]
no, 2.2.1 is only a security release - 2.4 is on its way ...

**Comment by boris-petrov** [comment]
I see, thanks! Looking forward to it then! :)

**Comment by marillat** [comment]
@boris-petrov 

Commit for  ffmpeg 6 is here https://github.com/gpac/gpac/commit/ba14e34dd7a3c4cef5a56962898e9f863dd4b4f3

**Comment by boris-petrov** [comment]
@marillat yes, thanks, I saw it but it's not in version 2.2.1 so one cannot compile it with FFmpeg 6. But no matter, I can wait for 2.4.
