### ISSUE TITLE
[bisected] v2.2.1 fails to build on ppc32 BigEndian

### ISSUE THREAD

**Issue by ernsteiswuerfel** [gpac/gpac#2758]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

This is Gentoo downstream bug report [#911634](https://bugs.gentoo.org/911634).

I also hit the issue when building git-v2.21 on the ppc32 chroot on my Talos II:
```
 # setarch ppc32 ./configure &&  setarch ppc32 make
make -C src all
make[1]: Entering directory '/root/builddir/gpac/src'
  CC evg/stencil.c
evg/stencil.c: In function 'get_pix_yuyv_10':
evg/stencil.c:1863:43: error: subscripted value is neither array nor pointer nor vector
 1863 | #define GET_LE_10BIT_LEFT_AS_8(_ptr) (_ptr[1] )
      |                                           ^
evg/stencil.c:2220:14: note: in expansion of macro 'GET_LE_10BIT_LEFT_AS_8'
 2220 |         vu = GET_LE_10BIT_LEFT_AS_8(p_src + _this->off_u);
      |              ^~~~~~~~~~~~~~~~~~~~~~
evg/stencil.c:1863:43: error: subscripted value is neither array nor pointer nor vector
 1863 | #define GET_LE_10BIT_LEFT_AS_8(_ptr) (_ptr[1] )
      |                                           ^
evg/stencil.c:2222:22: note: in expansion of macro 'GET_LE_10BIT_LEFT_AS_8'
 2222 |                 vy = GET_LE_10BIT_LEFT_AS_8(p_src + _this->off_y+4);
      |                      ^~~~~~~~~~~~~~~~~~~~~~
evg/stencil.c:1863:43: error: subscripted value is neither array nor pointer nor vector
 1863 | #define GET_LE_10BIT_LEFT_AS_8(_ptr) (_ptr[1] )
      |                                           ^
evg/stencil.c:2224:22: note: in expansion of macro 'GET_LE_10BIT_LEFT_AS_8'
 2224 |                 vy = GET_LE_10BIT_LEFT_AS_8(p_src + _this->off_y);
      |                      ^~~~~~~~~~~~~~~~~~~~~~
evg/stencil.c:1863:43: error: subscripted value is neither array nor pointer nor vector
 1863 | #define GET_LE_10BIT_LEFT_AS_8(_ptr) (_ptr[1] )
      |                                           ^
evg/stencil.c:2225:14: note: in expansion of macro 'GET_LE_10BIT_LEFT_AS_8'
 2225 |         vv = GET_LE_10BIT_LEFT_AS_8(p_src + _this->off_v);
      |              ^~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [../config.mak:182: evg/stencil.o] Error 1
make[1]: Leaving directory '/root/builddir/gpac/src'
make: *** [Makefile:13: all] Error 2
```
As git-v2.0.0 builds ok I was able to do a bisect which revealed the following commit:
```
 # git bisect bad
bf7e583bbac6930e3f47d5be37a717d307bb7102 is the first bad commit
commit bf7e583bbac6930e3f47d5be37a717d307bb7102
Author: jeanlf <jeanlf@gpac.io>
Date:   Thu Mar 31 13:45:31 2022 +0200

    added generic fallback in ffsws to evg

 src/evg/rast_soft.h       |   1 +
 src/evg/stencil.c         |  82 +++++++++++++++++++++++
 src/evg/surface.c         |  25 +++++++
 src/filters/ff_avf.c      |   4 +-
 src/filters/ff_common.c   |   6 +-
 src/filters/ff_common.h   |   2 +-
 src/filters/ff_enc.c      |   6 +-
 src/filters/ff_mx.c       |   2 +-
 src/filters/ff_rescale.c  | 163 ++++++++++++++++++++++++++++++++++++++++++----
 src/filters/reframe_av1.c |   4 +-
 src/jsmods/evg.c          |   4 +-
 11 files changed, 273 insertions(+), 26 deletions(-)
```
Some data about the build system:
```
Portage 3.0.59 (python 3.12.1-final-0, default/linux/ppc/17.0, gcc-11, glibc-2.38-r10, 6.7.4-gentoo-P9 ppc64)
=================================================================
System uname: Linux-6.7.4-gentoo-P9-ppc64-POWER9,_altivec_supported-with-glibc2.38
KiB Mem:    65662124 total,  49775716 free
KiB Swap:   16777212 total,  16777212 free
Timestamp of repository gentoo: Wed, 14 Feb 2024 08:00:01 +0000
Head commit of repository gentoo: df0756a3a68de415ebe1edd64ec5597c89765a20
sh dash 0.5.12
ld GNU ld (Gentoo 2.41 p4) 2.41.0
distcc 3.4 powerpc-unknown-linux-gnu [disabled]
app-misc/pax-utils:        1.3.7::gentoo
app-shells/bash:           5.1_p16-r6::gentoo
dev-build/autoconf:        2.13-r8::gentoo, 2.71-r6::gentoo
dev-build/automake:        1.16.5-r2::gentoo
dev-build/cmake:           3.27.9::gentoo
dev-build/libtool:         2.4.7-r1::gentoo
dev-build/make:            4.4.1-r1::gentoo
dev-build/meson:           1.3.0-r2::gentoo
dev-lang/perl:             5.38.2-r1::gentoo
dev-lang/python:           3.11.7::gentoo, 3.12.1_p1::gentoo
dev-lang/rust-bin:         1.74.1::gentoo
sys-apps/baselayout:       2.14-r2::gentoo
sys-apps/openrc:           0.53::gentoo
sys-apps/sandbox:          2.38::gentoo
sys-devel/binutils:        2.41-r3::gentoo
sys-devel/binutils-config: 5.5::gentoo
sys-devel/gcc:             11.4.1_p20240111::gentoo, 14.0.1_pre20240204-r1::gentoo
sys-devel/gcc-config:      2.11::gentoo
sys-devel/llvm:            17.0.6::gentoo
sys-kernel/linux-headers:  6.6::gentoo (virtual/os-headers)
sys-libs/glibc:            2.38-r10::gentoo
```
bisect.log attached. [bisect.log](https://github.com/gpac/gpac/files/14288901/bisect.log)

**Comment by aureliendavid** [comment]
Hello, 

This is a duplicate of #2363 which was fixed by https://github.com/gpac/gpac/commit/b0ad643014e567f47d1231771b473d25986c512e

The fix wasn't included in v2.2.1 which only included security patches, a new full release is coming soon. 

In the meantime you can either try with the latest master, or apply this patch

```patch
--- a/src/evg/stencil.c
+++ b/src/evg/stencil.c
@@ -1860,7 +1860,7 @@ u32 get_pix_yuv420p(EVG_Texture *_this,
 #define GET_LE_10BIT_AS_16(_ptr) ( (((u16)(_ptr)[1])<<8 | (u16)(_ptr)[0] ) << 6 )
 
 //#define GET_LE_10BIT_LEFT_AS_8(_ptr) ( (((u16)(_ptr)[1])<<8 | (u16)(_ptr)[0] ) >> 8 )
-#define GET_LE_10BIT_LEFT_AS_8(_ptr) (_ptr[1] )
+#define GET_LE_10BIT_LEFT_AS_8(_ptr) ((_ptr)[1] )
 #define GET_LE_10BIT_LEFT_AS_16(_ptr) ( (((u16)(_ptr)[1])<<8 | (u16)(_ptr)[0] ) & 0xFFC0 )
 
 #define GET_BE_10BIT_AS_8(_ptr) ( (*(u16 *)(_ptr)) >> 2 )
```

**Comment by ernsteiswuerfel** [comment]
Thanks!

I can confirm git master builds fine and the commit fixes v2.2.1.
