### ISSUE TITLE
os_net.c does not build with mingw-w64 gcc 14.2.0

### ISSUE THREAD

**Issue by 1480c1** [gpac/gpac#3133]
Error:
```c
D:/gcc/build/gpac-git/src/utils/os_net.c: In function 'gf_sk_get_ifce_ipv6_addr':
D:/gcc/build/gpac-git/src/utils/os_net.c:545:14: warning: variable 'force_ipv6' set but not used [-Wunused-but-set-variable]
  545 |         Bool force_ipv6 = GF_FALSE;
      |              ^~~~~~~~~~
D:/gcc/build/gpac-git/src/utils/os_net.c: In function 'gf_sk_server_mode':
D:/gcc/build/gpac-git/src/utils/os_net.c:4252:83: error: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
 4252 |                         if (setsockopt(sock->socket, IPPROTO_IPV6, IPV6_DONTFRAG, &val, sizeof(val) ) == -1) {
      |                                                                                   ^~~~
      |                                                                                   |
      |                                                                                   int *
In file included from D:/gcc/build/gpac-git/src/utils/os_net.c:44:
D:/gcc/msys64/mingw64/include/winsock2.h:1035:88: note: expected 'const char *' but argument is of type 'int *'
 1035 |   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
      |                                                                            ~~~~~~~~~~~~^~~~~~
D:/gcc/build/gpac-git/src/utils/os_net.c:4259:83: error: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
 4259 |                         if (setsockopt(sock->socket, IPPROTO_IP, IP_MTU_DISCOVER, &val, sizeof(val)) == -1) {
      |                                                                                   ^~~~
      |                                                                                   |
      |                                                                                   int *
D:/gcc/msys64/mingw64/include/winsock2.h:1035:88: note: expected 'const char *' but argument is of type 'int *'
 1035 |   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
      |                                                                            ~~~~~~~~~~~~^~~~~~
make[1]: *** [../config.mak:185: utils/os_net.o] Error 1
```

gcc 14 "upgraded" `-Wincompatible-pointer-types` to an error https://gcc.gnu.org/pipermail/gcc/2023-November/242943.html, and unfortunately, Windows decided to make the 4th option of `setsockopt()` to a `const char*`, with Linux disagreeing and saying it should be `const void*`.

Suggested fixes:
1. Add `-Wno-error=incompatible-pointer-types` to `CFLAGS` if gcc is greater than 14 and/or if Windows.
2. Always cast the 4th argument as `(const void *)` to allow it to compile with both Windows and Linux without warnings

**Comment by aureliendavid** [comment]
thank you for the report and analysis

casting as `char*` (which is what we were doing elsewhere) seems portable to both windows and linux so I went with that
